version: '3.1'

services:
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - 5050:80
    depends_on:
      - postgresql
    networks:
      - app_network

volumes:
  postgres_data:
    name: postgres_data

networks:
  app_network:
    name: app_network
    driver: bridge
